#ifndef AVIRISREADPLUGIN_GLOBAL_H
#define AVIRISREADPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(3DCUBEPLUGIN_LIBRARY)
#  define 3DCUBEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define 3DCUBEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AVIRISREADPLUGIN_GLOBAL_H
