#ifndef AVIRISREADPLUGIN_GLOBAL_H
#define AVIRISREADPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AVIRISREADPLUGIN_LIBRARY)
#  define AVIRISREADPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AVIRISREADPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AVIRISREADPLUGIN_GLOBAL_H
