#ifndef SPECTRALDISTANCE_GLOBAL_H
#define SPECTRALDISTANCE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SPECTRALDISTANCE_LIBRARY)
#  define SPECTRALDISTANCESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SPECTRALDISTANCESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SPECTRALDISTANCE_GLOBAL_H
