#ifndef HDF5FORMATLIB_GLOBAL_H
#define HDF5FORMATLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HDF5FORMATLIB_LIBRARY)
#  define HDF5FORMATLIB_EXPORT Q_DECL_EXPORT
#else
#  define HDF5FORMATLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // HDF5FORMATLIB_GLOBAL_H
